apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb
  labels:
    name: pvc-mariadb
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
