apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-qcm
spec:
  type: NodePort 
  selector:
    app: nginx-qcm
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 80
      nodePort: 30036
    - name: tcp-mysql
      port: 3306
      targetPort: 3306
      protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-qcm
  name: jenkins-service
spec:
  type: NodePort
  selector: 
    app: jenkins-qcm
  ports: 

  - name: jenkins-port1
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30037
 
  - name: jenkins-port2
    port: 50000
    protocol: TCP
    targetPort: 50000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb-qcm
  name: mariadb-service

spec:
  type: NodePort
  selector: 
    app: mariadb-qcm
  ports:
  - name: tcp-mysql
    port: 3306
    protocol: TCP
    targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-qcm
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana-qcm

  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30039



